# Generated by Django 5.2.6 on 2025-11-06 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_product'),
        ('Dealer', '0004_dealer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Dealer.dealer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Dealer.dealer'),
        ),
        migrations.DeleteModel(
            name='Dealer',
        ),
    ]
