# Generated by Django 5.2.6 on 2025-12-11 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_alter_transaction_dealer_alter_product_dealer_and_more'),
        ('Location', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('complaint', 'Complaint'), ('feedback', 'Feedback')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='Location.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
