# Generated by Django 5.2.6 on 2025-12-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
