# Generated by Django 5.2.6 on 2025-12-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_transaction_coupon_code_transaction_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
