# Generated by Django 5.2.6 on 2025-12-15 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_transaction_is_redeemed'),
        ('Pos', '0004_alter_pos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='redemption_pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_transactions', to='Pos.pos'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='redemption_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
