# Generated by Django 6.0.1 on 2026-03-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_transaction_redemption_pos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
