# Generated by Django 6.0.1 on 2026-04-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='coupon_code_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='serial_number_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
