# Generated by Django 6.0.1 on 2026-04-02 08:10

import Project1.encrypted_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_transaction_coupon_code_encrypted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='coupon_code_encrypted',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='serial_number_encrypted',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coupon_code',
            field=Project1.encrypted_field.EncryptedCharField(blank=True, db_column='coupon_code_encrypted', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='serial_number',
            field=Project1.encrypted_field.EncryptedCharField(blank=True, db_column='serial_number_encrypted', null=True),
        ),
    ]
