# Generated by Django 6.0.1 on 2026-04-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_remove_transaction_coupon_code_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='coupon_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
