"""Add is_confirmed and external_reference to Transaction

Generated by assistant.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_transaction_coupon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
