# Generated by Django 6.0.1 on 2026-05-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_add_is_confirmed_and_external_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='coupon_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='external_reference',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
