# Generated by Django 5.2.6 on 2025-11-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0002_alter_pos_pos_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pos',
            old_name='dealer',
            new_name='user',
        ),
    ]
