# Generated by Django 5.2.6 on 2025-11-06 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0003_user'),
        ('Pos', '0003_rename_dealer_pos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_devices', to='Location.user'),
        ),
    ]
