# Generated by Django 5.2.6 on 2025-09-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='is_active',
        ),
    ]
