# Generated by Django 5.2.6 on 2025-10-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0002_remove_dealer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
