# Generated by Django 5.2.6 on 2025-10-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0003_dealer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
